#Urls: http://localhost:5000;https://localhost:5001
Logging:
  LogLevel:
    Default: Information
    Microsoft.Hosting.Lifetime: Information
Spnego:
  Credentials:
    UserName: iwasvc
    Domain: almirex.dc
    Password: P@ssw0rd
  Kerberos:
    Kdc: ad.almirex.com
  Ldap:
    Claims: # see System.Security.Claims.ClaimTypes for standard claim types constants or use your own
      - LdapAttribute: memberof
        ClaimType: http://schemas.microsoft.com/ws/2008/06/identity/claims/role
    Host: ad.almirex.com # LDAP server 
    Port: 389
    UseSsl: true
    ValidateServerCertificate: false
    GroupsQuery: CN=Users,DC=almirex,DC=dc # LDAP OU for where groups should be loaded
    GroupsFilter: (objectClass=group) # LDAP filter to groups
    UsersQuery: CN=Users,DC=almirex,DC=dc # LDAP OU for users
    Credentials: # LDAP credentials (defaults to same as SPN credentials)
      UserName: ${Spnego:Credentials:UserName}
      Domain: ${Spnego:Credentials:Domain}
      Password: ${Spnego:Credentials:Password}
    RefreshFrequency: '00:00:10' # how often should LDAP be checked for changed in AD groups membership 
SpnManagement:
  LdapQuery: ${Spnego:Ldap:UsersQuery}